# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aykut's Homepage
email: aykutblt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal webpage.
baseurl: ""
url: "http://localhost:4000"
github_username:  aykutbulut

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
